In [29]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import preprocessing
import seaborn as sns
import sklearn
import sklearn.metrics
from sklearn.metrics import accuracy_score, mean_squared_error
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings('ignore')

In [6]:
data1  = pd.read_csv("/content/Depression-detection-using-Social-Media-Analysis/datasetPart1.csv")
data2  = pd.read_csv("/content/Depression-detection-using-Social-Media-Analysis/datasetPart2.csv")
values1=data1[['ItemID','Sentiment','SentimentSource','SentimentText','Analytic','Clout','Authentic','Tone','pronoun','ppron','i','we','you','shehe','they','ipron','article','prep','auxverb','adverb','conj','negate','verb','adj','compare','interrog','posemo','negemo','anx','anger','sad','social','family','friend','focuspast','focuspresent','focusfuture']]
values2=data2[['ItemID','Sentiment','SentimentSource','SentimentText','Analytic','Clout','Authentic','Tone','pronoun','ppron','i','we','you','shehe','they','ipron','article','prep','auxverb','adverb','conj','negate','verb','adj','compare','interrog','posemo','negemo','anx','anger','sad','social','family','friend','focuspast','focuspresent','focusfuture']]

In [8]:
dataframes=[values1,values2]
join=pd.concat(dataframes)
join.to_csv("output.csv")

In [9]:
data=pd.read_csv("output.csv")


In [11]:
data.head()

Unnamed: 0  ItemID  Sentiment SentimentSource  \
0           0       1          0    Sentiment140   
1           1       2          0    Sentiment140   
2           2       3          1    Sentiment140   
3           3       4          0    Sentiment140   
4           4       5          0    Sentiment140   

                                       SentimentText  Analytic  Clout  \
0                       is so sad for my APL frie...     25.89  50.00   
1                     I missed the New Moon trail...     93.26  13.32   
2                            omg its already 7:30 :O     46.37  50.00   
3            .. Omgaga. Im sooo  im gunna CRy. I'...     18.82   6.93   
4           i think mi bf is cheating on me!!!   ...     65.46  22.08   

   Authentic   Tone  pronoun  ...  negemo  anx  anger    sad  social  family  \
0       3.37   1.00    10.00  ...   10.00  0.0   0.00  10.00   10.00     0.0   
1      58.07   1.00    11.11  ...   11.11  0.0   0.00  11.11    0.00     0.0   
2       4.97  25.77    11.11  ...    0.00  0.0   0.00   0.00    0.00     0.0   
3      92.47   1.00    18.52  ...    3.70  0.0   0.00   3.70    0.00     0.0   
4      94.81   1.00    15.38  ...    7.69  0.0   7.69   0.00    7.69     0.0   

   friend  focuspast  focuspresent  focusfuture  
0   10.00       0.00         10.00          0.0  
1    0.00      11.11          0.00          0.0  
2    0.00      11.11          0.00          0.0  
3    0.00       7.41         14.81          3.7  
4    7.69       0.00         15.38          0.0  

[5 rows x 38 columns]

In [13]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8293 entries, 0 to 8292
Data columns (total 38 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Unnamed: 0       8293 non-null   int64  
 1   ItemID           8293 non-null   int64  
 2   Sentiment        8293 non-null   int64  
 3   SentimentSource  8293 non-null   object 
 4   SentimentText    8293 non-null   object 
 5   Analytic         8293 non-null   float64
 6   Clout            8293 non-null   float64
 7   Authentic        8293 non-null   float64
 8   Tone             8293 non-null   float64
 9   pronoun          8293 non-null   float64
 10  ppron            8293 non-null   float64
 11  i                8293 non-null   float64
 12  we               8293 non-null   float64
 13  you              8293 non-null   float64
 14  shehe            8293 non-null   float64
 15  they             8293 non-null   float64
 16  ipron            8293 non-null   float64
 17  article       

In [18]:
data_emotional_process=data[['posemo','negemo','anx','anger','sad']]
X_emo=data_emotional_process.iloc[:,1:].values
y_emo=data_emotional_process.iloc[:,0].values


In [20]:
X_emo

array([[10.  ,  0.  ,  0.  , 10.  ],
       [11.11,  0.  ,  0.  , 11.11],
       [ 0.  ,  0.  ,  0.  ,  0.  ],
       ...,
       [ 3.7 ,  0.  ,  3.7 ,  0.  ],
       [ 3.57,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ]])

In [31]:
from sklearn.model_selection import train_test_split;
X_train,X_test,y_train,y_test=train_test_split(X_emo,y_emo,test_size=0.2,random_state=0)


In [27]:
X_train

[[11.76  0.   11.76  0.  ]
 [ 4.17  0.    0.    4.17]
 [ 5.56  0.    0.    5.56]
 ...
 [ 0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.  ]
 [ 7.41  0.    3.7   0.  ]]


In [30]:
from sklearn.ensemble import RandomForestRegressor
clf=RandomForestRegressor(n_estimators=9,random_state=45,min_samples_split=5)
clf.fit(X_train,y_train)
y_pred=clf.predict(X_test)
mean_squared_error(y_test,y_pred)

30.418430281923666